# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: fastapi
      POSTGRES_USER: fastapi
      POSTGRES_DB: fastapi
    ports:
      - 5432:5432
